backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "sections"
    label: "Sections"
    files:
      - label: "Front Page"
        name: "front_page"
        editor:
          preview: false
        file: "content/sections/front_page.json"
        fields:
          - label: "Value"
            name: "value"
            widget: "string"

          - label: "Heading"
            name: "heading"
            widget: "string"

          - label: "Company Description"
            name: "company_description"
            widget: "text"

          - label: "Two Images"
            name: "two_images"
            widget: "list"
            max: 2
            min: 1
            field: {
              label: "Image",
              name: "image",
              widget: "image"
            }


      - label: "About"
        name: "about"
        file: "content/sections/about.json"
        editor:
          preview: false
        fields:
          - label: "Certifications Images"
            name: "certifications_images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: image
              - label: "URL"
                name: "url"
                widget: string
          - { label: "Description", name: "description", widget: "markdown" }
          - label: "Certifications"
            name: "certifications"
            widget: "list"
            fields: 
              - label: "Organisation"
                name: "organisation"
                widget: string
              - label: "Qualification"
                name: "qualification"
                widget: string
              - label: "URL"
                name: "url"
                widget: string
          - label: "Office Image"
            name: "office_image"
            widget: image

      - label: "Contact"
        name: "contact"
        file: "content/sections/contact.json"
        fields:
          - label: "External Contact Methods"
            name: "external_contact_methods"
            widget: "list"
            fields:
              - label: "Icon"
                name: "icon"
                widget: image
              - label: "URL"
                name: "url"
                widget: string
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Additional Information"
            name: "additional_information"
            widget: markdown
            buttons: [bold, italic]


      - label: "Logo"
        name: "logo"
        file: "content/sections/logo.json"
        fields:
          - label: "Logo Image"
            name: "logo_image"
            widget: image

      - label: "Categories"
        name: "categories"
        file: "content/sections/categories.json"
        editor:
          preview: false
        fields:
          - label: "Category Items"
            name: "category_items"
            widget: list
            fields:
              - label: "Section Name"
                name: "section_name"
                widget: string
              - label: "Section Icon"
                name: "section_icon"
                widget: image
              - label: "Section Images"
                name: "section_images"
                widget: list
                fields: 
                  - label: "Section Image"
                    name: "section_image"
                    widget: image
                  - label: "Footnote"
                    name: "footnote"
                    widget: string
              - label: "Section Description"
                name: "section_description"
                widget: markdown
                buttons: [bold, italic, numbered-list, bulleted-list]



